services:
  nestapp1:
    build:
      context: ./api-otel-1
      dockerfile: Dockerfile
    env_file:
      - '.env'
    ports:
      - ${NEST_API1_PORT}
    depends_on:
      - redis
      - jaeger
    networks:
      - rede-app

  redis:
    image: redis:6-alpine
    ports:
      - ${REDIS_PORT}
    networks:
      - rede-app

  jaeger:
    image: jaegertracing/all-in-one:1.58
    ports:
      - ${JAEGER_PORT1}
      - ${JAEGER_PORT2}
      - ${JAEGER_PORT3}
      - ${JAEGER_PORT4}
      - ${JAEGER_PORT5}
    networks:
      - rede-app

networks:
  rede-app:
    driver: bridge